---
- name: Download the repo key
  ansible.builtin.get_url:
    url: https://packages.redis.io/gpg
    dest: /etc/apt/trusted.gpg.d/redis.asc
  tags:
    - redis

- name: Install the apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/redis.asc] https://packages.redis.io/deb jammy main"
    state: present
    filename: redis
  tags:
    - redis

- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - apt-transport-https
      - gnupg
      - redis-server
      - nfs-common
      - rdiff-backup
      - software-properties-common
  tags:
    - redis

- import_tasks: appdir_and_mountpoints.yml
  vars:
    appdirs:
      - path: /opt
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host }}:{{ backup_path }}'
        dest: /backups
        owner: '{{ backup_owner }}'
        group: '{{ backup_group }}'
  tags:
    - redis

- name: Check that /var/lib/redis/dump.rdb exists
  ansible.builtin.stat:
    path: /var/lib/redis/dump.rdb
  register: redis_db
  tags:
    - redis

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup -r now --force /backups/redis/ /var/lib/redis
  ignore_errors: true
  when: not redis_db.stat.exists
  tags:
    - redis

- name: copy the config
  ansible.builtin.copy:
    src: redis.conf
    dest: /etc/redis/redis.conf
    mode: 0640
    owner: redis
    group: redis
  tags:
    - redis

- name: Start and enable the service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: redis-server
  tags:
    - redis

- import_tasks: backup.yml
  vars:
  vars:
    backup_src: '/var/lib/redis'
    backup_dest: '/backups/redis'
  tags:
    - redis
