---
- name: Download the repo key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
  tags:
    - grafana

- name: Install the apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present
    filename: grafana
  tags:
    - grafana

- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - freeipa-client
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - rdiff-backup
  tags:
    - grafana

- import_tasks: idm_client_setup.yml
  vars:
    username: grafana-krb5
    password: '{{ grafana.password }}'
    homedirectory: /opt/grafana
    loginshell: /usr/bin/bash
  tags:
    - grafana

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - grafana

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: grafana-krb5
    local_username: grafana
  tags:
    - grafana

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0775'
        owner: grafana
        group: grafana
  tags:
    - grafana

- name: Check that /var/lib/grafana/grafana.db exists
  ansible.builtin.stat:
    path: /var/lib/grafana/grafana.db
  register: grafana_db
  tags:
    - grafana

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/grafana/ /var/lib/grafana
  ignore_errors: true
  when: not grafana_db.stat.exists
  tags:
    - grafana

- name: Install grafana
  ansible.builtin.apt:
    pkg: grafana
  tags:
    - grafana

- import_tasks: unbound_external_dns.yml
  tags:
    - grafana

- import_tasks: reverse_proxy.yml
  tags:
    - grafana

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/var/lib/grafana'
    backup_dest: '/backups/grafana'
    backup_dir_name: grafana
    backup_owner: grafana-krb5
    backup_group: grafana-krb5
    cron_owner: grafana
  tags:
    - grafana
