- hosts: init
  gather_facts: no
  roles:
    - host_manager
    - generic_redirects

- hosts: proxmox_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - apt
    - zfs_features
    - cpufreq
    - postfix
    - udev
    - containers
    - proxmox_redirects

# This sets up PCIe passthrough for VMs on these hosts. The hosts are defined
# in global_vars/init/proxmox_hosts.yml
- hosts: pve001
  gather_facts: yes
  remote_user: root
  roles:
    - role: pcie_passthrough
      architecture: amd

- hosts: pve005
  gather_facts: yes
  remote_user: root
  roles:
    - role: pcie_passthrough
      architecture: intel
      enable_gvt: true

# This sets up the containers
- hosts: caddy_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - caddy

- hosts: dns_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - dns

- hosts: esphome_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - esphome

- hosts: grafana_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - grafana

- hosts: lidarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - lidarr

- hosts: mqtt_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - mqtt

- hosts: netboot_xyz_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - netboot_xyz

- hosts: node_red_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - node_red

- hosts: plex_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - plex

- hosts: octoprint_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - octoprint

- hosts: radarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - radarr

- hosts: redis_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - redis

- hosts: sabnzbd_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - sabnzbd

- hosts: sonarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - sonarr

- hosts: syslog_ng_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - syslog_ng

- hosts: tautulli_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - tautulli

- hosts: tdarr_node_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - tdarr_node

- hosts: tdarr_server_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - tdarr_server

- hosts: zwave_js_ui_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - zwave_js_ui

- hosts: home_assistant_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - home_assistant

# This needs to be last so that all containers can have Postfix set up too
- hosts: postfix_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - postfix
