- hosts: init
  gather_facts: no
  roles:
    - host_manager

- hosts: proxmox_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - apt
    - zfs_features
    - cpufreq
    - postfix
    - containers

- hosts: esphome_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - esphome

- hosts: lidarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - lidarr

- hosts: octoprint_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - octoprint

# This needs to be last so that all containers can have Postfix set up too
- hosts: postfix_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - postfix
