- hosts: init
  gather_facts: no
  roles:
    - host_manager

- hosts: proxmox_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - apt
    - zfs_features
    - cpufreq
    - postfix
    - containers

# This sets up PCIe passthrough for VMs on these hosts. The hosts are defined
# in global_vars/init/proxmox_hosts.yml
- hosts: pve001
  gather_facts: yes
  remote_user: root
  roles:
    - role: pcie_passthrough
      architecture: amd

- hosts: pve005
  gather_facts: yes
  remote_user: root
  roles:
    - role: pcie_passthrough
      architecture: intel
      enable_gvt: true

- hosts: esphome_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - esphome

- hosts: grafana_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - grafana

- hosts: lidarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - lidarr

- hosts: netboot_xyz_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - netboot_xyz

- hosts: octoprint_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - octoprint

- hosts: radarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - radarr

- hosts: sabnzbd_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - sabnzbd

- hosts: sonarr_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - sonarr

- hosts: tautulli_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - tautulli

- hosts: tdarr_server_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - tdarr_server

# This needs to be last so that all containers can have Postfix set up too
- hosts: postfix_hosts
  gather_facts: yes
  remote_user: root
  roles:
    - postfix
