---
- name: Download the repo key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/trusted.gpg.d/nodesource.asc
  tags:
    - node_red

- name: Install the apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/nodesource.asc] https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    filename: nodesource
  tags:
    - node_red

- import_tasks: ubuntu_setup.yml
  vars:
    username: node_red
    groupname: node_red
    shell: /usr/sbin/nologin
    packages:
      - apt-transport-https
      - build-essential
      - freeipa-client
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - nodejs
      - rdiff-backup
  tags:
    - node_red

- import_tasks: idm_client_setup.yml
  vars:
    username: node-red
    password: '{{ node_red.password }}'
    homedirectory: /config
    loginshell: /usr/bin/bash
  tags:
    - node_red

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - node_red

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: node-red
  tags:
    - node_red

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: node-red
        group: node-red
      - path: /opt/node_red
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0775'
        owner: node-red
        group: node-red
  tags:
    - node_red

- name: Install "node-red" node.js package.
  community.general.npm:
    name: node-red
    path: /opt/node_red
  register: node_red_install
  tags:
    - node_red

- name: Check that /config/settings.js exists
  ansible.builtin.stat:
    path: /config/settings.js
  register: settings_js
  tags:
    - node_red

- import_tasks: rsyslog_conf.yml
  vars:
    syslog_identifier: node-red
  tags:
    - node_red

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/node-red/ /config
  ignore_errors: true
  when: not settings_js.stat.exists
  tags:
    - node_red

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: node-red.service
    state: '{{ node_red_install.changed | ternary("restarted", "started") }}'
  tags:
    - node_red

- import_tasks: unbound_external_dns.yml
  tags:
    - node_red

- import_tasks: reverse_proxy.yml
  tags:
    - node_red

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/node-red'
    backup_dir_name: node_red
    backup_owner: node-red
    backup_group: node-red
  tags:
    - node_red
