---
- name: Remove pve-enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
    state: absent
    update_cache: false
  tags:
    - apt

- name: Remove ceph repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
    state: absent
    update_cache: false
  tags:
    - apt

- name: Add pve-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
    state: present
    update_cache: false
  tags:
    - apt

- name: Add ceph-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
    state: present
    update_cache: false
  tags:
    - apt

- name: "Gather installed packages"
  ansible.builtin.package_facts:
    manager: auto
  tags:
    - apt

- name: "Install pve fake subscription"
  when: '"pve-fake-subscription" not in ansible_facts.packages'
  block:
    - name: Get newest pve-fake-subscription release
      ansible.builtin.uri:
        url: https://api.github.com/repos/Jamesits/pve-fake-subscription/releases/latest
        return_content: true
      register: json_reponse

    - name: Create tmpdir
      ansible.builtin.tempfile:
        state: directory
      register: tmpdir

    - name: Download pve-fake-subscription
      ansible.builtin.get_url:
        url: "{{ json_reponse.json.assets[0].browser_download_url }}"
        dest: "{{ tmpdir.path }}"
        mode: "0644"
      register: download

    - name: Install pve-fake-subscription
      ansible.builtin.apt:
        deb: "{{ download.dest }}"
  tags:
    - apt

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: true
  tags:
    - apt

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
