---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - freeipa-client
      - kstart
      - mosquitto
      - mosquitto-clients
      - nfs-common
      - nfs4-acl-tools
      - rdiff-backup
  tags:
    - mqtt

- import_tasks: idm_client_setup.yml
  vars:
    username: mqtt
    password: '{{ mqtt.password }}'
    homedirectory: /config
    loginshell: /usr/bin/bash
  tags:
    - mqtt

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - mqtt

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: mqtt
    local_username: mosquitto
  tags:
    - mqtt

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: mosquitto
        group: mosquitto
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0775'
        owner: mqtt
        group: mqtt
  tags:
    - mqtt

- name: Copy the config file
  ansible.builtin.copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/mosquitto.conf
    mode: 0644
    owner: root
    group: root
  register: mosquitto_conf
  tags:
    - mqtt

- name: Copy the password file
  ansible.builtin.copy:
    src: pwfile
    dest: /etc/mosquitto/pwfile
    mode: 0600
    owner: mosquitto
    group: mosquitto
  register: mosquitto_pw
  tags:
    - mqtt

- name: Check that /config/mosquitto.db exists
  ansible.builtin.stat:
    path: /config/mosquitto.db
  register: mosquitto_db
  tags:
    - mqtt

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/mqtt/ /config
  ignore_errors: true
  when: not mosquitto_db.stat.exists
  tags:
    - mqtt

- name: Start and enable the service
  ansible.builtin.systemd:
    state: '{{ mosquitto_conf.changed or mosquitto_pw.changed | ternary("restarted", "started") }}'
    daemon_reload: true
    enabled: true
    name: mosquitto.service
  tags:
    - mqtt

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/mqtt'
    backup_dir_name: mqtt
    backup_owner: mqtt
    backup_group: mqtt
    cron_user: mosquitto
  tags:
    - mqtt
