---
- name: Create the application directories
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    mode: 0775
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ appdirs }}'
  when: appdirs is defined

- name: Create mountpoints
  ansible.builtin.file:
    path: '{{ item.dest }}'
    state: directory
    mode: 0775
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
  loop: '{{ mountpoints }}'
  when: mountpoints is defined

- name: Mount the NFS volumes
  ansible.posix.mount:
    src: '{{ item.src }}'
    path: '{{ item.dest }}'
    opts: rw
    state: mounted
    fstype: nfs
  loop: '{{ mountpoints }}'
  when: mountpoints is defined
