---
- name: 'Store traefik info for {{ item.service }}'
  ansible.builtin.set_fact:
    reverse_proxy_hostname: '{{ item.reverse_proxy_hostname }}'
    caddy_service: '{{ item.service }}'
    caddy_lb_url: '{{ item.lb_url }}'

- name: copy the caddy dynamic config files
  template:
    src: 'caddy-router.toml'
    dest: '{{ caddy_config_path }}/{{ caddy_service }}.toml'
    mode: 0644
    owner: '{{ caddy_uid }}'
    group: '{{ caddy_gid }}'
  delegate_to: '{{ caddy_host }}'
  remote_user: '{{ caddy_user }}'
  become: true
