---
- name: 'Store reverse proxy info for {{ reverse_proxy_service }}'
  ansible.builtin.set_fact:
    caddy_service: '{{ reverse_proxy_service }}'
    caddy_lb_url: '{{ reverse_proxy_url_prefix | default("http") }}://{{ inventory_hostname }}:{{ service_port }}'

- name: copy the caddy dynamic config files
  template:
    src: 'caddy-router.toml'
    dest: '{{ caddy_config_path }}/{{ caddy_service }}.toml'
    mode: 0644
    owner: caddy
    group: caddy
  loop: '{{ caddy_host_ips }}'
  loop_control:
    loop_var: caddy_host_ip
  delegate_to: '{{ caddy_host_ip }}'
  remote_user: '{{ caddy_user }}'
  become: true
