---
- name: 'store unbound internal DNS info for {{ container_hostname }}'
  ansible.builtin.set_fact:
    unbound_ip_address: '{{ container_ip }}'
    unbound_fqdn: '{{ container_hostname | default(omit) }}'
    unbound_domain: '{{ container_hostname.split(".", 1) [1] | default(omit) }}'

- name: copy the unbound internal zone file entry
  template:
    src: 'unbound-internal-dns.conf'
    dest: '{{ unbound_config_path }}/{{ unbound_domain }}/{{ unbound_fqdn }}.conf'
    mode: 0644
    owner: '{{ unbound_uid }}'
    group: '{{ unbound_gid }}'
  delegate_to: '{{ unbound_host_ip }}'
  remote_user: '{{ unbound_user }}'
  become: true
  loop: '{{ unbound_hosts }}'
  loop_control:
    loop_var: unbound_host_ip
  when: unbound_fqdn is defined
