---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - binutils
      - freeipa-client
      - kstart
      - libchromaprint-tools
      - mediainfo
      - nfs-common
      - nfs4-acl-tools
      - rdiff-backup
      - sqlite3
  tags:
    - lidarr

- import_tasks: idm_client_setup.yml
  vars:
    username: lidarr
    groupname: media
    password: '{{ lidarr.password }}'
    homedirectory: /opt/lidarr
    loginshell: /usr/bin/bash
  tags:
    - lidarr

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - lidarr

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: lidarr
    groupname: media
    wanted_by_unit: lidarr.service
  tags:
    - lidarr

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: lidarr
        group: lidarr
      - path: /opt/lidarr
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        owner: lidarr
        group: lidarr
      - src: '{{ music_host_v4 }}:{{ music_path_v4 }}'
        dest: /music
        mode: '0775'
      - src: '{{ download_host_v4 }}:{{ download_path_v4 }}'
        dest: /downloads
        mode: '0775'
  tags:
    - lidarr

- name: Get Lidarr URL version
  ansible.builtin.set_fact:
    web_version: "{{ lidarr_master_url | regex_search('/v([\\d.]+)/', '\\1') | first }}"
  tags:
    - lidarr

- name: Check that /opt/lidarr/Lidarr.Core.dll exists
  ansible.builtin.stat:
    path: /opt/lidarr/Lidarr.Core.dll
  register: lidarr_core_dll
  tags:
    - lidarr

- name: Get the installed version
  ansible.builtin.shell:
    cmd: "strings /opt/lidarr/Lidarr.Core.dll | grep Version= | grep Lidarr.Common | head -1 | awk -F'Version=' '{ print $2 }' | awk -F, '{print $1}'"
  register: file_version
  when: lidarr_core_dll.stat.exists
  changed_when: false
  tags:
    - lidarr

- name: Set a default Lidarr file version
  ansible.builtin.set_fact:
    file_version:
      stdout: 'missing'
  when: file_version.stdout is undefined
  tags:
    - lidarr

- name: Download latest lidarr
  ansible.builtin.get_url:
    url: '{{ lidarr_master_url }}'
    dest: /opt/lidarr.tar.gz
  when: web_version != file_version.stdout
  tags:
    - lidarr

- name: Extract the lidarr tarball
  ansible.builtin.unarchive:
    src: /opt/lidarr.tar.gz
    dest: /opt/lidarr
    remote_src: true
    extra_opts:
      - '--strip-components=1'
  when: web_version != file_version.stdout
  tags:
    - lidarr

- name: Remove the tarball
  ansible.builtin.file:
    path: /opt/lidarr.tar.gz
    state: absent
  when: web_version != file_version.stdout
  tags:
    - lidarr

- name: Check that /config/lidarr.db exists
  ansible.builtin.stat:
    path: /config/lidarr.db
  register: lidarr_db
  tags:
    - lidarr

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/lidarr/ /config/
  ignore_errors: true
  become: true
  become_user: lidarr
  when: not lidarr_db.stat.exists
  tags:
    - lidarr

- import_tasks: rsyslog_conf.yml
  vars:
    syslog_identifier: lidarr
  tags:
    - lidarr

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'lidarr.service'
    state: '{{ (web_version != file_version.stdout) | ansible.builtin.ternary("restarted", "started") }}'
  tags:
    - lidarr

- import_tasks: unbound_external_dns.yml
  tags:
    - lidarr

- import_tasks: reverse_proxy.yml
  tags:
    - lidarr

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/lidarr'
    backup_dir_name: lidarr
    backup_owner: lidarr
    backup_group: lidarr
  tags:
    - lidarr
