---
# https://github.com/caddyserver/caddy/releases
caddy_version: v2.8.4
# https://go.dev/dl/
caddy_go_version: 1.23.1
caddy_dns_cloudflare: github.com/caddy-dns/cloudflare
caddy_dns_route53: github.com/caddy-dns/route53
caddy_dns_duckdns: github.com/caddy-dns/duckdns
# https://github.com/kovidgoyal/calibre/releases
calibre_version: 7.23.0
# https://github.com/janeczku/calibre-web/releases
calibre_web_version: 0.6.24
# https://github.com/DNSCrypt/dnscrypt-proxy/releases
dnscrypt_proxy_version: 2.1.5
# https://github.com/jgraph/drawio/releases
drawio_version: v24.7.17
# From: $ . /home/home_assistant/.bashrc-pyenv && pyenv install --list
home_assistant_pyenv_version: 3.12.3
# https://github.com/home-assistant/core/releases
homeassistant_version: 2024.12.5
# https://github.com/Lidarr/Lidarr/releases
lidarr_version: 2.8.2.4493
# https://github.com/netbootxyz/netboot.xyz/releases
netboot_xyz_version: 2.0.83
# https://github.com/sct/overseerr/releases
overseer_version: 1.33.2
# https://github.com/pi-hole/pi-hole/releases
pihole_src_url: https://github.com/pi-hole/pi-hole/archive/refs/tags/v5.18.3.tar.gz
# https://www.openssl.org/source/
openssl_src_url: https://www.openssl.org/source/openssl-3.1.6.tar.gz
# https://github.com/Radarr/Radarr/releases
radarr_version: 5.16.3.9541
# https://github.com/Readarr/Readarr/releases
readarr_version: 0.4.6.2711
# https://github.com/sabnzbd/sabnzbd/releases
sabnzbd_version: 4.4.1
# https://github.com/Sonarr/Sonarr/releases
sonarr_version: 4.0.11.2680
# https://github.com/syncthing/syncthing/releases
syncthing_version: v1.28.1
# https://go.dev/dl/
syncthing_go_version: 1.23.4
# https://github.com/syslog-ng/syslog-ng/releases
syslog_ng_version: 4.8.1
# Versions come from https://github.com/Tautulli/Tautulli/releases
tautulli_version: v2.15.0
# Versions come from https://f000.backblazeb2.com/file/tdarrs/versions.json
tdarr_node_package_url: https://f000.backblazeb2.com/file/tdarrs/versions/2.27.02/linux_x64/Tdarr_Node.zip
tdarr_server_package_url: https://f000.backblazeb2.com/file/tdarrs/versions/2.27.02/linux_x64/Tdarr_Server.zip
# Tomcat versions come from https://tomcat.apache.org/download-90.cgi
tomcat_version: 9.0.98
# Transmission versions come from https://github.com/transmission/transmission/releases
transmission_version: 4.0.6
# https://github.com/NLnetLabs/unbound/tags
unbound_version: 1.22.0
# https://github.com/valkey-io/valkey/releases
valkey_version: 8.0.1
# https://github.com/Koenkk/zigbee2mqtt/releases
zigbee2mqtt_version: 1.42.0
# https://github.com/zwave-js/zwave-js-ui/releases
zwave_js_ui_version: 9.29.0
