---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - binutils
      - freeipa-client
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - rdiff-backup
  tags:
    - radarr

- import_tasks: idm_client_setup.yml
  vars:
    username: radarr
    groupname: media
    password: '{{ radarr.password }}'
    homedirectory: /opt/radarr
    loginshell: /usr/bin/bash
  tags:
    - radarr

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - radarr

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: radarr
    groupname: media
  tags:
    - radarr

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: radarr
        group: radarr
      - path: /opt/radarr
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        owner: radarr
        group: radarr
      - src: '{{ movies_host_v4 }}:{{ movies_path_v4 }}'
        dest: /movies
        mode: '0775'
      - src: '{{ download_host_v4 }}:{{ download_path_v4 }}'
        dest: /downloads
        mode: '0775'
  tags:
    - radarr

- name: Get Radarr URL version
  ansible.builtin.set_fact:
    web_version: "{{ radarr_master_url | regex_search('v([\\d.]+)/', '\\1') | first }}"
  tags:
    - radarr

- name: Check that /opt/radarr/Radarr.Core.dll exists
  ansible.builtin.stat:
    path: /opt/radarr/Radarr.Core.dll
  register: radarr_core_dll
  tags:
    - radarr

- name: Get the installed version
  ansible.builtin.shell:
    cmd: "strings /opt/radarr/Radarr.Core.dll | grep Version= | grep Radarr.Common | head -1 | awk -F'Version=' '{ print $2 }' | awk -F, '{print $1}'"
  register: file_version
  when: radarr_core_dll.stat.exists
  changed_when: false
  tags:
    - radarr

- name: Set a default Radarr file version
  ansible.builtin.set_fact:
    file_version:
      stdout: 'missing'
  when: file_version.stdout is undefined
  tags:
    - radarr

- name: Download latest radarr
  ansible.builtin.get_url:
    url: '{{ radarr_master_url }}'
    dest: /opt/radarr.tar.gz
  when: web_version != file_version.stdout
  tags:
    - radarr

- name: Extract the radarr tarball
  ansible.builtin.unarchive:
    src: /opt/radarr.tar.gz
    dest: /opt/radarr
    remote_src: true
    extra_opts:
      - '--strip-components=1'
  when: web_version != file_version.stdout
  tags:
    - radarr

- name: Remove the tarball
  ansible.builtin.file:
    path: /opt/radarr.tar.gz
    state: absent
  when: web_version != file_version.stdout
  tags:
    - radarr

- name: Check that /config/radarr.db exists
  ansible.builtin.stat:
    path: /config/radarr.db
  register: radarr_db
  tags:
    - radarr

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/radarr/ /config/
  ignore_errors: true
  become: true
  become_user: sonarr
  when: not radarr_db.stat.exists
  tags:
    - radarr

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'radarr.service'
    state: '{{ (web_version != file_version.stdout) | ansible.builtin.ternary("restarted", "started") }}'
  tags:
    - radarr

- import_tasks: unbound_external_dns.yml
  tags:
    - radarr

- import_tasks: reverse_proxy.yml
  tags:
    - radarr

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/radarr'
    backup_dir_name: radarr
    backup_owner: radarr
    backup_group: radarr
  tags:
    - radarr
