---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - freeipa-client
      - git
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rdiff-backup
  tags:
    - esphome

- import_tasks: idm_client_setup.yml
  vars:
    username: esphome
    groupname: esphome
    password: '{{ esphome.password }}'
    homedirectory: /opt/esphome
    loginshell: /usr/bin/bash
  tags:
    - esphome

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - esphome

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: esphome
  tags:
    - esphome

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: esphome
        group: esphome
      - path: /opt/esphome
        owner: esphome
        group: esphome
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0775'
        owner: esphome
        group: esphome
  tags:
    - esphome

- name: Create esphome application directory
  ansible.builtin.file:
    path: /opt/esphome/ESPHome
    state: directory
    mode: '0755'
  become: true
  become_user: esphome
  tags:
    - esphome

- name: Ensure the virtual environment is created
  ansible.builtin.shell:
    cmd: python3 -m venv venv
    chdir: /opt/esphome/ESPHome/
  become: true
  become_user: esphome
  tags:
    - esphome

- name: Install Esphome and its dependencies into the venv
  ansible.builtin.pip:
    name:
      - esphome
      - esptool
      - setuptools
      - tornado
    state: latest
    virtualenv: /opt/esphome/ESPHome/venv
    virtualenv_site_packages: true
  become: true
  become_user: esphome
  register: pip_install
  tags:
    - esphome

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'esphome.service'
    state: '{{ pip_install.changed | ternary("restarted", "started") }}'
  tags:
    - esphome

- import_tasks: unbound_external_dns.yml
  tags:
    - esphome

- import_tasks: reverse_proxy.yml
  tags:
    - esphome

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/esphome'
    backup_dir_name: esphome
    backup_owner: esphome
    backup_group: esphome
  tags:
    - esphome
