---
- import_tasks: ubuntu_setup.yml
  vars:
    username: esphome
    uid: 1000
    shell: '/bin/bash'
    packages:
      - git
      - nfs-common
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rdiff-backup
  tags:
    - esphome

- import_tasks: appdir_and_mountpoints.yml
  vars:
    appdirs:
      - path: /config
        owner: esphome
        group: esphome
      - path: /opt/esphome
        owner: esphome
        group: esphome
    mountpoints:
      - src: '{{ backup_host }}:{{ backup_path }}'
        dest: /backups
        owner: '{{ backup_owner }}'
        group: '{{ backup_group }}'
  tags:
    - esphome

- name: Create esphome application directory
  ansible.builtin.file:
    path: /opt/esphome/ESPHome
    state: directory
    mode: '0755'
  become: true
  become_user: esphome
  tags:
    - esphome

- name: Ensure the virtual environment is created
  ansible.builtin.shell:
    cmd: python3 -m venv venv
    chdir: /opt/esphome/ESPHome/
  become: true
  become_user: esphome
  tags:
    - esphome

- name: Install Esphome and its dependencies into the venv
  ansible.builtin.pip:
    name:
      - esphome
      - esptool
      - tornado
    state: latest
    virtualenv: /opt/esphome/ESPHome/venv
    virtualenv_site_packages: true
  become: true
  become_user: esphome
  register: pip_install
  tags:
    - esphome

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'esphome.service'
    state: '{{ pip_install.changed | ternary("restarted", "started") }}'
  tags:
    - esphome

- import_tasks: reverse_proxy.yml
  tags:
    - esphome

- import_tasks: backup.yml
  vars:
  vars:
    backup_src: '/config'
    backup_dest: '/backups/esphome'
  tags:
    - esphome
