---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - apt-transport-https
      - gnupg
      - transmission-daemon
      - nfs-common
      - rdiff-backup
      - software-properties-common
  tags:
    - transmission

- import_tasks: appdir_and_mountpoints.yml
  vars:
    appdirs:
      - path: /var/lib/transmission-daemon/bin/
        owner: debian-transmission
        group: debian-transmission
    mountpoints:
      - src: '{{ download_host }}:{{ download_path }}'
        dest: /downloads
        mode: '0775'
        owner: '{{ download_uid }}'
        group: '{{ media_gid }}'
  tags:
    - transmission

- name: Stop the service
  ansible.builtin.systemd:
    state: stopped
    enabled: true
    name: transmission-daemon
  tags:
    - transmission

- name: copy the config
  ansible.builtin.copy:
    src: settings.json
    dest: /etc/transmission-daemon/settings.json
    mode: 0600
    owner: debian-transmission
    group: debian-transmission
  tags:
    - transmission

- name: Start and enable the service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: transmission-daemon
  tags:
    - transmission

- name: copy remove-done-torrent script
  ansible.builtin.copy:
    src: 'remove-done-torrent'
    dest: '/var/lib/transmission-daemon/bin/remove-done-torrent'
    mode: 0700
    owner: debian-transmission
    group: debian-transmission
  tags:
    - transmission

- name: update blocklist cron job
  ansible.builtin.cron:
    name: blocklist update
    minute: "0"
    hour: "23"
    user: debian-transmission
    job: 'transmission-remote --blocklist-update &> /dev/null'
    cron_file: transmission-blocklist-update
  tags:
    - transmission

- name: remove done torrent cron job
  ansible.builtin.cron:
    name: remove done torrent
    minute: '*/5'
    user: debian-transmission
    job: '/var/lib/transmission/bin/remove-done-torrent &> /dev/null'
    cron_file: remove-done-torrent
  tags:
    - transmission

- import_tasks: reverse_proxy.yml
  tags:
    - transmission
