---
- name: Download the repo key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
  tags:
    - tailscale

- name: Install the apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main"
    state: present
    filename: tailscale.list
  tags:
    - tailscale

- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - apt-transport-https
      - gnupg
      - tailscale
      - software-properties-common
  tags:
    - tailscale

- name: persist the sysctl config for networking
  ansible.builtin.copy:
    src: 98-tailscale.conf
    dest: /etc/sysctl.d/98-tailscale.conf
    mode: 0755
    owner: root
    group: root
  register: tailscale_sysctl
  tags:
    - tailscale

- name: enable the sysctl changes
  ansible.builtin.command:
    cmd: sysctl -p /etc/sysctl.d/98-tailscale.conf
  when: tailscale_sysctl.changed
  tags:
    - tailscale
