---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - binutils
      - freeipa-client
      - kstart
      - libmono-corlib4.5-cil
      - libmono-microsoft-csharp4.0-cil
      - libmono-posix4.0-cil
      - libmono-system-componentmodel-dataannotations4.0-cil
      - libmono-system-configuration-install4.0-cil
      - libmono-system-configuration4.0-cil
      - libmono-system-core4.0-cil
      - libmono-system-data-datasetextensions4.0-cil
      - libmono-system-data4.0-cil
      - libmono-system-identitymodel4.0-cil
      - libmono-system-io-compression4.0-cil
      - libmono-system-net-http4.0-cil
      - libmono-system-numerics4.0-cil
      - libmono-system-runtime-serialization4.0-cil
      - libmono-system-security4.0-cil
      - libmono-system-servicemodel4.0a-cil
      - libmono-system-serviceprocess4.0-cil
      - libmono-system-transactions4.0-cil
      - libmono-system-web4.0-cil
      - libmono-system-xml-linq4.0-cil
      - libmono-system-xml4.0-cil
      - libmono-system4.0-cil
      - mediainfo
      - mono-runtime
      - nfs-common
      - nfs4-acl-tools
      - rdiff-backup
      - xmlstarlet
  tags:
    - sonarr

- import_tasks: idm_client_setup.yml
  vars:
    username: sonarr
    groupname: media
    password: '{{ sonarr.password }}'
    homedirectory: /opt/sonarr
    loginshell: /usr/bin/bash
  tags:
    - sonarr

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - sonarr

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: sonarr
    groupname: media
  tags:
    - sonarr

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: sonarr
        group: media
      - path: /opt/sonarr
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0770'
        owner: sonarr
        group: sonarr
      - src: '{{ tv_host_v4 }}:{{ tv_path_v4 }}'
        dest: /tv
        mode: '0775'
      - src: '{{ download_host_v4 }}:{{ download_path_v4 }}'
        dest: /downloads
        mode: '0775'
  tags:
    - sonarr

- name: Check that /opt/sonarr/Sonarr.Core.dll exists
  ansible.builtin.stat:
    path: /opt/sonarr/Sonarr.Core.dll
  register: sonarr_core_dll
  tags:
    - sonarr

- name: Get the installed version
  ansible.builtin.shell:
    cmd: "strings /opt/sonarr/Sonarr.Core.dll | grep Version= | grep Sonarr.Common | head -1 | awk -F'Version=' '{ print $2 }' | awk -F, '{print $1}'"
  register: file_version
  when: sonarr_core_dll.stat.exists
  changed_when: false
  tags:
    - sonarr

- name: Set a default Sonarr file version
  ansible.builtin.set_fact:
    file_version:
      stdout: 'missing'
  when: file_version.stdout is undefined
  tags:
    - sonarr

- name: Download latest sonarr
  ansible.builtin.get_url:
    url: 'https://github.com/Sonarr/Sonarr/releases/download/v{{ sonarr_version }}/Sonarr.main.{{ sonarr_version }}.linux-x64.tar.gz'
    dest: /opt/sonarr.tar.gz
  when: sonarr_version != file_version.stdout
  tags:
    - sonarr

- name: Extract the sonarr tarball
  ansible.builtin.unarchive:
    src: /opt/sonarr.tar.gz
    dest: /opt/sonarr
    remote_src: true
    extra_opts:
      - '--strip-components=1'
  when: sonarr_version != file_version.stdout
  tags:
    - sonarr

- name: Remove the tarball
  ansible.builtin.file:
    path: /opt/sonarr.tar.gz
    state: absent
  when: sonarr_version != file_version.stdout
  tags:
    - sonarr

- name: Check that /config/sonarr.db exists
  ansible.builtin.stat:
    path: /config/sonarr.db
  register: sonarr_db
  tags:
    - sonarr

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/sonarr/ /config/
  ignore_errors: true
  become: true
  become_user: sonarr
  when: not sonarr_db.stat.exists
  tags:
    - sonarr

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'sonarr.service'
    state: '{{ (sonarr_version != file_version.stdout) | ansible.builtin.ternary("restarted", "started") }}'
  tags:
    - sonarr

- import_tasks: unbound_external_dns.yml
  tags:
    - sonarr

- import_tasks: reverse_proxy.yml
  tags:
    - sonarr

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/sonarr'
    backup_dir_name: sonarr
    backup_owner: sonarr
    backup_group: sonarr
  tags:
    - sonarr
