---
proxmox_hosts:
  pve001:
    api_host: '{{ pve001.api_host }}'
    api_user: '{{ pve001.api_user }}'
    api_password: '{{ pve001.api_password }}'
    zfs_pools:
      - rpool
      - tank
  pve002:
    api_host: '{{ pve002.api_host }}'
    api_user: '{{ pve002.api_user }}'
    api_password: '{{ pve002.api_password }}'
    zfs_pools:
      - rpool
  pve004:
    api_host: '{{ pve004.api_host }}'
    api_user: '{{ pve004.api_user }}'
    api_password: '{{ pve004.api_password }}'
    zfs_pools:
      - rpool
      - tank
  pve005:
    api_host: '{{ pve005.api_host }}'
    api_user: '{{ pve005.api_user }}'
    api_password: '{{ pve005.api_password }}'
    zfs_pools:
      - rpool
    containers:
      - hostname: '{{ caddy0.hostname }}'
        vmid: '{{ caddy0.vmid }}'
        container_ip: '{{ caddy0.container_ip }}'
        password: '{{ caddy0.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 8
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: caddy
      - hostname: '{{ dns0.hostname }}'
        vmid: '{{ dns0.vmid }}'
        container_ip: '{{ dns0.container_ip }}'
        password: '{{ dns0.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: dns
        traefik_service: 'dns0'
        traefik_hostname: '{{ dns0.traefik_hostname }}'
        service_port: 80
      - hostname: '{{ netboot_xyz.hostname }}'
        vmid: '{{ netboot_xyz.vmid }}'
        password: '{{ netboot_xyz.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: netboot_xyz
        traefik_service: netboot_xyz
        traefik_hostname: '{{ netboot_xyz.traefik_hostname }}'
        service_port: 80
      - hostname: '{{ radarr.hostname }}'
        vmid: '{{ radarr.vmid }}'
        password: '{{ radarr.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: 'radarr'
        traefik_service: 'radarr'
        traefik_hostname: '{{ radarr.traefik_hostname }}'
        service_port: 7878
      - hostname: '{{ sonarr.hostname }}'
        vmid: '{{ sonarr.vmid }}'
        password: '{{ sonarr.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: sonarr
        traefik_service: sonarr
        traefik_hostname: '{{ sonarr.traefik_hostname }}'
        service_port: 8989
      - hostname: '{{ syslog_ng.hostname }}'
        vmid: '{{ syslog_ng.vmid }}'
        container_ip: '{{ syslog_ng.container_ip }}'
        password: '{{ syslog_ng.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: syslog_ng
      - hostname: '{{ tdarr_node.hostname }}'
        vmid: '{{ tdarr_node.vmid }}'
        password: '{{ tdarr_node.password }}'
        unprivileged: false
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 10
        memory: 16384
        swap: 4096
        storage: 'local-zfs'
        rootfs_size: 8
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_changes:
          - 'lxc.cgroup2.devices.allow: c 226:* rwm'
          - 'lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file'
          - 'lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file'
        config_task: 'tdarr_node'
      - hostname: '{{ tdarr_server.hostname }}'
        vmid: '{{ tdarr_server.vmid }}'
        password: '{{ tdarr_server.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 4096
        swap: 4096
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: tdarr_server
        traefik_service: tdarr
        traefik_hostname: '{{ tdarr_server.traefik_hostname }}'
        service_port: 8265
      - hostname: '{{ tautulli.hostname }}'
        vmid: '{{ tautulli.vmid }}'
        password: '{{ tautulli.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: tautulli
        traefik_service: tautulli
        traefik_hostname: '{{ tautulli.traefik_hostname }}'
        service_port: 8181
      - hostname: '{{ home_assistant.hostname }}'
        vmid: '{{ home_assistant.vmid }}'
        password: '{{ home_assistant.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 2
        memory: 4096
        swap: 4096
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: home_assistant
  pve006:
    api_host: '{{ pve006.api_host }}'
    api_user: '{{ pve006.api_user }}'
    api_password: '{{ pve006.api_password }}'
    zfs_pools:
      - rpool
    containers:
      - hostname: '{{ dns1.hostname }}'
        vmid: '{{ dns1.vmid }}'
        container_ip: '{{ dns1.container_ip }}'
        password: '{{ dns1.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: dns
        traefik_service: 'dns1'
        traefik_hostname: '{{ dns1.traefik_hostname }}'
        service_port: 80
      - hostname: '{{ octoprint.hostname }}'
        vmid: '{{ octoprint.vmid }}'
        password: '{{ octoprint.password }}'
        unprivileged: false
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 512
        swap: 512
        storage: 'local-zfs'
        rootfs_size: 8
        features:
          - 'nesting=1'
        proxmox_default_behavior: compatibility
        config_changes:
          - 'lxc.cgroup2.devices.allow: c 189:1 rwm'
          - 'lxc.mount.entry: /dev/bus/usb/003/002 dev/bus/usb/003/002 none bind,optional,create=file'
          - 'lxc.cgroup2.devices.allow: c 166:* rwm'
          - 'lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0 none bind,optional,create=file'
        config_task: octoprint
        traefik_service: octoprint
        traefik_hostname: '{{ octoprint.traefik_hostname }}'
        service_port: 5000
      - hostname: '{{ sabnzbd.hostname }}'
        vmid: '{{ sabnzbd.vmid }}'
        password: '{{ sabnzbd.password }}'
        onboot: true
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: sabnzbd
        traefik_service: sabnzbd
        traefik_hostname: '{{ sabnzbd.traefik_hostname }}'
        service_port: 8080
      - hostname: '{{ lidarr.hostname }}'
        vmid: '{{ lidarr.vmid }}'
        password: '{{ lidarr.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 32
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: 'lidarr'
        traefik_service: 'lidarr'
        traefik_hostname: '{{ lidarr.traefik_hostname }}'
        service_port: 8686
      - hostname: '{{ esphome.hostname }}'
        vmid: '{{ esphome.vmid }}'
        password: '{{ esphome.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: esphome
        traefik_service: esphome
        traefik_hostname: '{{ esphome.traefik_hostname }}'
        service_port: 6052
      - hostname: '{{ grafana.hostname }}'
        vmid: '{{ grafana.vmid }}'
        password: '{{ grafana.password }}'
        ostemplate: 'ubuntu-22.04-standard_22.04-1_amd64.tar.zst'
        cores: 1
        memory: 1024
        swap: 1024
        storage: 'local-zfs'
        rootfs_size: 16
        features:
          - 'nesting=1'
          - 'mount=nfs'
        proxmox_default_behavior: compatibility
        config_task: grafana
        traefik_service: grafana
        traefik_hostname: '{{ grafana.traefik_hostname }}'
        service_port: 3000
