---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - freeipa-client
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - p7zip-full
      - p7zip-rar
      - par2
      - python3
      - python3-pip
      - python3-venv
      - rdiff-backup
      - unrar
      - unzip
  tags:
    - sabnzbd

- import_tasks: idm_client_setup.yml
  vars:
    username: sabnzbd
    groupname: media
    password: '{{ sabnzbd.password }}'
    homedirectory: /opt/sabnzbd
    loginshell: /usr/bin/bash
  tags:
    - sabnzbd

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - sabnzbd

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: sabnzbd
    groupname: media
  tags:
    - sabnzbd

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: /config
        owner: sabnzbd
        group: sabnzbd
      - path: /opt/python
        owner: sabnzbd
        group: sabnzbd
      - path: /opt/sabnzbd
        owner: sabnzbd
        group: sabnzbd
    mountpoints:
      - src: '{{ backup_host_v4 }}:{{ backup_path_v4 }}'
        dest: /backups
        mode: '0775'
        owner: sabnzbd
        group: sabnzbd
      - src: '{{ download_host_v4 }}:{{ download_path_v4 }}'
        dest: /downloads
        mode: '0775'
        owner: sabnzbd
        group: media
  tags:
    - sabnzbd

- name: Get Sabnzbd URL version
  ansible.builtin.set_fact:
    web_version: "{{ sabnzbd_package_url | regex_search('download/([\\d.]+)/', '\\1') | first }}"
  tags:
    - sabnzbd

- name: Check that /opt/sabnzbd/sabnzbd/version.py exists
  ansible.builtin.stat:
    path: /opt/sabnzbd/sabnzbd/version.py
  register: sabnzbd_version
  tags:
    - sabnzbd

- name: Get the installed version
  ansible.builtin.shell:
    cmd: "/usr/bin/grep ^__version__ /opt/sabnzbd/sabnzbd/version.py | awk -F\\\" '{print $2}'"
  register: file_version
  when: sabnzbd_version.stat.exists
  changed_when: false
  tags:
    - sabnzbd

- name: Set a default Sabnzbd file version
  ansible.builtin.set_fact:
    file_version:
      stdout: 'missing'
  when: file_version.stdout is undefined
  tags:
    - sabnzbd

- name: Download sabnzbd
  ansible.builtin.get_url:
    url: '{{ sabnzbd_package_url }}'
    dest: /opt/sabnzbd/sabnzbd.tar.gz
  when: web_version != file_version.stdout
  tags:
    - sabnzbd

- name: Extract the sabnzbd package
  ansible.builtin.unarchive:
    src: /opt/sabnzbd/sabnzbd.tar.gz
    dest: /opt/sabnzbd
    remote_src: true
    extra_opts:
      - '--strip-components=1'
  no_log: true
  when: web_version != file_version.stdout
  tags:
    - sabnzbd

- name: Remove the tarball
  ansible.builtin.file:
    path: /opt/sabnzbd/sabnzbd.tar.gz
    state: absent
  when: web_version != file_version.stdout
  tags:
    - sabnzbd

- name: Ensure the virtual environment is created
  ansible.builtin.shell:
    cmd: python3 -m venv python
    chdir: /opt/
  become: true
  become_user: sabnzbd
  changed_when: false
  tags:
    - sabnzbd

- name: Install the requirements
  ansible.builtin.pip:
    requirements: /opt/sabnzbd/requirements.txt
    virtualenv: /opt/python
    virtualenv_site_packages: true
  become: true
  become_user: sabnzbd
  tags:
    - sabnzbd

- name: Check that /config/sabnzbd.ini exists
  ansible.builtin.stat:
    path: /config/sabnzbd.ini
  register: sabnzbd_ini
  tags:
    - sabnzbd

- name: Restore the backup (if it exists and is necessary)
  ansible.builtin.command:
    cmd: rdiff-backup --api-version 201 --force restore /backups/sabnzbd/ /config/
  ignore_errors: true
  become: true
  become_user: sabnzbd
  when: not sabnzbd_ini.stat.exists
  tags:
    - sabnzbd

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'sabnzbd.service'
    state: '{{ (web_version != file_version.stdout) | ansible.builtin.ternary("restarted", "started") }}'
  tags:
    - sabnzbd

- import_tasks: unbound_external_dns.yml
  tags:
    - sabnzbd

- import_tasks: reverse_proxy.yml
  tags:
    - sabnzbd

- import_tasks: backup_v4.yml
  vars:
    backup_src: '/config'
    backup_dest: '/backups/sabnzbd'
    backup_dir_name: sabnzbd
    backup_owner: sabnzbd
    backup_group: sabnzbd
  tags:
    - sabnzbd
