---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - freeipa-client
      - handbrake-cli
      - intel-opencl-icd
      - kstart
      - nfs-common
      - nfs4-acl-tools
      - ocl-icd-libopencl1
      - rdiff-backup
      - unzip
      - va-driver-all
  tags:
    - tdarr_node

- import_tasks: idm_client_setup.yml
  vars:
    username: tdarr
    groupname: media
    homedirectory: /opt/tdarr
    loginshell: /usr/bin/bash
  tags:
    - tdarr_node

- import_tasks: idm_service_setup.yml
  vars:
    service_principal_name: 'nfs/{{ container_hostname }}'
  tags:
    - tdarr_node

- import_tasks: idm_systemd_user_setup.yml
  vars:
    username: tdarr
    groupname: media
  tags:
    - tdarr_node

- import_tasks: appdir_and_mountpoints_v4.yml
  vars:
    appdirs:
      - path: '/opt/tdarr/Tdarr_Node'
        owner: root
        group: root
      - path: '/opt/tdarr/Tdarr_Node/assets/app/plugins'
        owner: tdarr
        group: media
      - path: '/opt/tdarr/configs'
        owner: tdarr
        group: media
      - path: '/opt/tdarr/logs'
        owner: tdarr
        group: media
    mountpoints:
      - src: '{{ movies_host_v4 }}:{{ movies_path_v4 }}'
        dest: /movies
        mode: '0775'
      - src: '{{ tv_host_v4 }}:{{ tv_path_v4 }}'
        dest: /tv
        mode: '0775'
      - src: '{{ transcode_host_v4 }}:{{ transcode_path_v4 }}'
        dest: /opt/tdarr/transcode-cache
        mode: '0775'
  tags:
    - tdarr_node

- name: Get tdarr server URL version
  ansible.builtin.set_fact:
    web_version: "{{ tdarr_node_package_url | regex_search('versions/([\\d.]+)/', '\\1') | first }}"
  tags:
    - tdarr_node

- name: Check that /opt/tdarr/version exists
  ansible.builtin.stat:
    path: /opt/tdarr/version
  register: tdarr_version
  tags:
    - tdarr_node

- name: Get the installed version
  ansible.builtin.shell:
    cmd: "cat /opt/tdarr/version"
  register: file_version
  when: tdarr_version.stat.exists
  changed_when: false
  tags:
    - tdarr_node

- name: Set a default tdarr file version
  ansible.builtin.set_fact:
    file_version:
      stdout: 'missing'
  when: file_version.stdout is undefined
  tags:
    - tdarr_node

- name: Download tdarr
  ansible.builtin.get_url:
    url: '{{ tdarr_node_package_url }}'
    dest: /opt/tdarr/Tdarr_Node.zip
  when: web_version != file_version.stdout
  tags:
    - tdarr_node

- name: Extract the tdarr updater
  ansible.builtin.unarchive:
    src: /opt/tdarr/Tdarr_Node.zip
    dest: /opt/tdarr/Tdarr_Node
    remote_src: true
  no_log: true
  when: web_version != file_version.stdout
  tags:
    - tdarr_node

- name: Remove the zip file
  ansible.builtin.file:
    path: /opt/tdarr/Tdarr_Node.zip
    state: absent
  when: web_version != file_version.stdout
  tags:
    - tdarr_node

- name: update the version
  template:
    src: version.txt
    dest: '/opt/tdarr/version'
    mode: 0644
    owner: root
    group: root
  when: web_version != file_version.stdout
  tags:
    - tdarr_node

- name: copy the tdarr-node configuration
  template:
    src: 'Tdarr_Node_Config.json'
    dest: '/opt/tdarr/configs'
    mode: 0644
    owner: root
    group: root
  tags:
    - tdarr_node

- import_tasks: systemd_unit.yml
  vars:
    systemd_unit: 'tdarr-node.service'
    state: '{{ (web_version != file_version.stdout) | ansible.builtin.ternary("restarted", "started") }}'
  tags:
    - tdarr_node

