---
- import_tasks: ubuntu_setup.yml
  vars:
    packages:
      - ansible
      - git
      - apache2
      - nfs-common
      - rdiff-backup
      - tftpd-hpa
  tags:
    - netboot_xyz

- import_tasks: appdir_and_mountpoints.yml
  vars:
    appdirs:
      - path: /opt/netboot.xyz
        owner: root
        group: root
    mountpoints:
      - src: '{{ backup_host }}:{{ backup_path }}'
        dest: /backups
        owner: '{{ backup_owner }}'
        group: '{{ backup_group }}'
  tags:
    - netboot_xyz

- name: Get netboot.xyz URL version
  ansible.builtin.set_fact:
    web_version: "{{ netboot_xyz_package_url | regex_search('/([\\d.]+).tar.gz', '\\1') | first }}"
  tags:
    - netboot_xyz

- name: Check that /opt/netboot.xyz/version.txt exists
  ansible.builtin.stat:
    path: /opt/netboot.xyz/version.txt
  register: version_txt
  tags:
    - netboot_xyz

- name: Get the installed version
  command: cat /opt/netboot.xyz/version.txt
  register: version_txt_cmd
  when: version_txt.stat.exists
  changed_when: false
  tags:
    - netboot_xyz

- name: Set the netboot.xyz file version
  ansible.builtin.set_fact:
    installed_version: '{{ version_txt_cmd.stdout_lines[0] | default("missing") }}'
  tags:
    - netboot_xyz

- name: Download latest netboot.xyz
  ansible.builtin.get_url:
    url: '{{ netboot_xyz_package_url }}'
    dest: /opt/netboot_xyz.tar.gz
  when: web_version != installed_version
  tags:
    - netboot_xyz

- name: Extract the netboot.xyz tarball
  ansible.builtin.unarchive:
    src: /opt/netboot_xyz.tar.gz
    dest: /opt/netboot.xyz
    remote_src: true
    extra_opts:
      - '--strip-components=1'
  when: web_version != installed_version
  tags:
    - netboot_xyz

- name: Remove the tarball
  ansible.builtin.file:
    path: /opt/netboot_xyz.tar.gz
    state: absent
  when: web_version != installed_version
  tags:
    - netboot_xyz

- name: Build netboot.xyx
  ansible.builtin.command:
    cmd: ansible-playbook -i inventory site.yml
  args:
    chdir: /opt/netboot.xyz
  when: web_version != installed_version
  tags:
    - netboot_xyz

- name: Start and enable the apache service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: apache2.service
  tags:
    - netboot_xyz

- name: Set the TFTP directory
  lineinfile:
    backrefs: true
    path: /etc/default/tftpd-hpa
    regexp: '^TFTP_DIRECTORY=".*"$'
    line: 'TFTP_DIRECTORY="/var/www/html"'
  tags:
    - netboot_xyz

- name: Start and enable the tftpd-hpa service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: tftpd-hpa.service
  tags:
    - netboot_xyz

- import_tasks: unbound_external_dns.yml
  tags:
    - netboot_xyz

- import_tasks: reverse_proxy.yml
  tags:
    - netboot_xyz
